spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: lee
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
